### ISSUE TITLE
Not works on NPM 1.3.10

### ISSUE THREAD

**Issue by delirehberi** [anonrig/slack-manager#1]
I get this error when i try run with `npm start` command.

```
/home/delirehberi/slack-manager/src/index.js:8
const config = require('./config');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

Error changing if i try run with this  command `node --harmony src/index.js` : 

```
/home/delirehberi/slack-manager/src/index.js:28
    .startRTM((err, bot, payload) => {
                                   ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by anonrig** [comment]
Can you tell your Node & Npm version @delirehberi

**Comment by delirehberi** [comment]
Node: v0.10.25
Npm: 1.3.10

**Comment by anonrig** [comment]
Slack-Manager uses ES6 - EcmaScript 6 and therefore should be used with Node 4.0.0 and up. Thank you for your reply, we should add `engine` tag to package.json to indicate supported node versions.
